//thinking of leaving out stuff with spaces for now
//nahhhhhhh
//list is from https://a-z-animals.com/animals/
//function to get all the animal names on that page
const getAnimalList = () => {
  let animals = [];
  document.querySelectorAll(`.container > ul > li`).forEach(e=>{
    if (!e.innerText.includes("Human"))
      animals.push(e.innerText.match(/^([\w\s\-’'\u00C0-\u024F]+)/gi)[0]
        .replaceAll("’", "'")
        .normalize("NFKD").replace(/[\u0300-\u036F]/g, "")
        .trim()
      );
  });
  console.log(animals);
};
const animalList = [
  "Aardvark",
  "Aardwolf",
  "Abyssinian",
  "Abyssinian Guinea Pig",
  "Acadian Flycatcher",
  "Achrioptera Manga",
  "Ackie Monitor",
  "Addax",
  "Adelie Penguin",
  "Admiral Butterfly",
  "Aesculapian Snake",
  "Affenpinscher",
  "Afghan Hound",
  "African Bullfrog",
  "African Bush Elephant",
  "African Civet",
  "African Clawed Frog",
  "African Elephant",
  "African Fish Eagle",
  "African Forest Elephant",
  "African Golden Cat",
  "African Grey Parrot",
  "African Jacana",
  "African Palm Civet",
  "African Penguin",
  "African Sugarcane Borer",
  "African Tree Toad",
  "African Wild Dog",
  "Africanized bee",
  "Agama Lizard",
  "Agkistrodon Contortrix",
  "Agouti",
  "Aidi",
  "Ainu",
  "Airedale Terrier",
  "Airedoodle",
  "Akbash",
  "Akita",
  "Akita Shepherd",
  "Alabai",
  "Alaskan Husky",
  "Alaskan Klee Kai",
  "Alaskan Malamute",
  "Alaskan Pollock",
  "Alaskan Shepherd",
  "Albacore Tuna",
  "Albatross",
  "Albertonectes",
  "Albino",
  "Aldabra Giant Tortoise",
  "Alligator Gar",
  "Allosaurus",
  "Allosaurus",
  "Alpaca",
  "Alpine Dachsbracke",
  "Alpine Goat",
  "Alusky",
  "Amano Shrimp",
  "Amargasaurus",
  "Amazon Parrot",
  "Amazon River Dolphin",
  "Amazon Tree Boa",
  "Amazonian Royal Flycatcher",
  "Amberjack",
  "Ambrosia Beetle",
  "American Alligator",
  "American Alsatian",
  "American Bulldog",
  "American Bully",
  "American Cocker Spaniel",
  "American Cockroach",
  "American Coonhound",
  "American Dog Tick",
  "American Eel",
  "American Eskimo Dog",
  "American Foxhound",
  "American Hairless Terrier",
  "American Leopard Hound",
  "American Paddlefish",
  "American Pit Bull Terrier",
  "American Pugabull",
  "American Pygmy Goat",
  "American Robin",
  "American Staffordshire Terrier",
  "American Toad",
  "American Water Spaniel",
  "American Wirehair",
  "Amethystine Python",
  "Amphicoelias Fragillimus",
  "Amur Leopard",
  "Anaconda",
  "Anatolian Shepherd Dog",
  "Anchovies",
  "Andrewsarchus",
  "Angelfish",
  "Angelshark",
  "Angled Sunbeam Caterpillar",
  "Anglerfish",
  "Angora Ferret",
  "Angora Goat",
  "Anhinga",
  "Anna's Hummingbird",
  "Anole Lizard",
  "Anomalocaris",
  "Ant",
  "Antarctic Scale Worm",
  "Anteater",
  "Antelope",
  "Anteosaurus",
  "Antiguan Racer Snake",
  "Aoudad Sheep",
  "Ape",
  "Apennine Wolf",
  "Appenzeller Dog",
  "Apple Head Chihuahua",
  "Apple Moth",
  "Arabian Cobra",
  "Arabian Wolf",
  "Arafura File Snake",
  "Arambourgiania",
  "Arapaima",
  "Archaeoindris",
  "Archaeopteryx",
  "Archaeotherium",
  "Archelon Turtle",
  "Archerfish",
  "Arctic Char",
  "Arctic Fox",
  "Arctic Hare",
  "Arctic Wolf",
  "Arctodus",
  "Arctotherium",
  "Argentavis Magnificens",
  "Argentine Black and White Tegu",
  "Argentine Horned Frog",
  "Argentinosaurus",
  "Arizona Bark Scorpion",
  "Arizona Black Rattlesnake",
  "Arizona Blonde Tarantula",
  "Arizona Coral Snake",
  "Armadillo",
  "Armadillo Lizard",
  "Armenian Gampr",
  "Armored Catfish",
  "Armyworm",
  "Arsinoitherium",
  "Arthropleura",
  "Aruba Rattlesnake",
  "Ashy Mining Bee",
  "Asian Arowana",
  "Asian Carp",
  "Asian Cockroach",
  "Asian Elephant",
  "Asian Giant Hornet",
  "Asian Lady Beetle",
  "Asian Longhorn Beetle",
  "Asian Palm Civet",
  "Asian Vine Snake",
  "Asian Water Monitor",
  "Asiatic Black Bear",
  "Asp",
  "Asp Caterpillar",
  "Assassin Bug",
  "Assassin Snail",
  "Atlantic Cod",
  "Atlantic Salmon",
  "Atlantic Sturgeon",
  "Atlas Beetle",
  "Atlas Moth",
  "Aurochs",
  "Aussiedoodle",
  "Aussiedor",
  "Aussiepom",
  "Australian Bulldog",
  "Australian Cattle Dog",
  "Australian Cockroach",
  "Australian Firehawk",
  "Australian Flathead Perch",
  "Australian Gecko",
  "Australian Kelpie Dog",
  "Australian Labradoodle",
  "Australian Mist",
  "Australian Retriever",
  "Australian Shepherd",
  "Australian Shepherd Mix",
  "Australian Terrier",
  "Australopithecus",
  "Australorp Chicken",
  "Avocet",
  "Axanthic Ball Python",
  "Axolotl", //this one is so based
  "Ayam Cemani",
  "Aye-aye",
  "Azawakh",
  "Babirusa",
  "Baboon",
  "Bactrian Camel",
  "Badger",
  "Bagle",
  "Bagworm Moth",
  "Bagworm Moth Caterpillar",
  "Baird's Rat Snake",
  "Bald Eagle",
  "Baleen Whale",
  "Balinese",
  "Balkan Lynx",
  "Ball Python",
  "Bamboo Rat",
  "Bamboo Shark",
  "Bamboo Worms",
  "Banana Ball Python",
  "Banana Cinnamon Ball Python",
  "Banana Eel",
  "Banana Spider",
  "Banded Krait",
  "Banded Palm Civet",
  "Banded Water Snake",
  "Bandicoot",
  "Banjo Catfish",
  "Barb",
  "Barbet",
  "Barbut's Cuckoo Bumblebee",
  "Barinasuchus",
  "Bark Beetle",
  "Bark Scorpion",
  "Barn Owl",
  "Barn Spider",
  "Barn Swallow",
  "Barnacle",
  "Barnevelder",
  "Barosaurus",
  "Barracuda",
  "Barramundi Fish",
  "Barred Owl",
  "Barreleye Fish",
  "Barylambda",
  "Basenji Dog",
  "Basenji Mix",
  "Basilisk Lizard",
  "Basilosaurus",
  "Basking Shark",
  "Bass",
  "Bassador",
  "Basset Fauve de Bretagne",
  "Basset Hound",
  "Bassetoodle",
  "Bat",
  "Bat-Eared Fox",
  "Batfish",
  "Bavarian Mountain Hound",
  "Baya",
  "Bea-Tzu",
  "Beabull",
  "Beagador",
  "Beagle",
  "Beagle Mix",
  "Beagle Shepherd",
  "Beaglier",
  "Beago",
  "Bear",
  "Bearded Collie",
  "Bearded Dragon",
  "Bearded Fireworm",
  "Bearded Vulture",
  "Beaski",
  "Beauceron",
  "Beauty rat snake",
  "Beaver",
  "Bed Bugs",
  "Bedlington Terrier",
  "Bee",
  "Bee-Eater",
  "Beefalo",
  "Beetle",
  "Beewolf wasp",
  "Belgian Canary",
  "Belgian Laekenois",
  "Belgian Malinois",
  "Belgian Malinois Mix",
  "Belgian Sheepdog",
  "Belgian Shepherd",
  "Belgian Tervuren",
  "Belted Kingfisher",
  "Beluga Sturgeon",
  "Beluga Sturgeon",
  "Bengal Tiger",
  "Bergamasco",
  "Berger Blanc Suisse",
  "Berger Picard",
  "Bernedoodle",
  "Bernese Mountain Dog",
  "Bernese Mountain Dog Mix",
  "Bernese Shepherd",
  "Betta Fish",
  "Bhutan Takin",
  "Bichir",
  "Bichon Frise",
  "Bichpoo",
  "Biewer Terrier",
  "Bigfin Reef Squid",
  "Bighorn Sheep",
  "Bilby",
  "Binturong",
  "Bird",
  "Bird Of Paradise",
  "Bird Snake",
  "Birman",
  "Biscuit Beetle",
  "Bismarck Ringed Python",
  "Bison",
  "Black And Tan Coonhound",
  "Black and White Warbler",
  "Black Aphids",
  "Black Bass",
  "Black Crappie",
  "Black Dragon Lizard",
  "Black German Shepherd",
  "Black Mamba",
  "Black Marlin",
  "Black Mouth Cur",
  "Black Pastel Ball Python",
  "Black Rat Snake",
  "Black Rhinoceros",
  "Black Russian Terrier",
  "Black Sea Bass",
  "Black Swallowtail",
  "Black Swallowtail Caterpillar",
  "Black Tarantula",
  "Black Throat Monitor",
  "Black Wasp",
  "Black Widow Spider",
  "Black Witch Moth",
  "Black-Bellied Whistling Duck",
  "Black-Capped Chickadee",
  "Black-Footed Ferret",
  "Black-headed python",
  "Black-Tailed Rattlesnake",
  "Blackburnian Warbler",
  "Blackfin Tuna",
  "Blacknose Shark",
  "Blackpoll Warbler",
  "Blacktip Reef Shark",
  "Blacktip Shark",
  "Bladefin Basslet",
  "Blanket Octopus",
  "Blind Snake",
  "Blister Beetle",
  "Blister Beetle",
  "Blobfish",
  "Blood Python",
  "Bloodhound",
  "Blowfly",
  "Blue Andalusian",
  "Blue Belly Lizard",
  "Blue Catfish",
  "Blue Death Feigning Beetle",
  "Blue Dragon Sea Slug",
  "Blue Eyed Pleco",
  "Blue German Shepherd",
  "Blue Gray Gnatcatcher",
  "Blue grosbeak",
  "Blue Iguana",
  "Blue Jay",
  "Blue Lacy Dog",
  "Blue Nose Pit Bull",
  "Blue Picardy Spaniel",
  "Blue Racer",
  "Blue Shark",
  "Blue Tanager",
  "Blue Tang",
  "Blue Tit",
  "Blue Whale",
  "Blue-Ringed Octopus",
  "Bluefin Tuna",
  "Bluefish",
  "Bluegill",
  "Bluetick Coonhound",
  "Boas",
  "Bobcat",
  "Bobolink",
  "Boelen's python",
  "Boer Goat",
  "Boerboel",
  "Boggle",
  "Boglen Terrier",
  "Boiga",
  "Bolivian Anaconda",
  "Bolognese Dog",
  "Bombardier Beetle",
  "Bombay",
  "Bonefish",
  "Bongo",
  "Bonito Fish",
  "Bonnethead Shark",
  "Bonobo",
  "Booby",
  "Boomslang",
  "Booted Bantam",
  "Borador",
  "Border Collie",
  "Border Collie Mix",
  "Border Terrier",
  "Bordoodle",
  "Borkie",
  "Bornean Orangutan",
  "Borneo Elephant",
  "Boskimo",
  "Boston Terrier",
  "Bottlenose Dolphin",
  "Bouvier Des Flandres",
  "Bowfin",
  "Bowhead Whale",
  "Box Jellyfish",
  "Box Tree Moth",
  "Box Turtle",
  "Box-Headed Blood Bee",
  "Boxachi",
  "Boxador",
  "Boxer Dog",
  "Boxer Mix",
  "Boxerdoodle",
  "Boxfish",
  "Boxsky",
  "Boxweiler",
  "Boykin Spaniel",
  "Bracco Italiano",
  "Brachiosaurus",
  "Brahma Chicken",
  "Brahminy Blindsnake",
  "Braque du Bourbonnais",
  "Braque Francais",
  "Brazilian Black Tarantula",
  "Brazilian Terrier",
  "Brazilian Treehopper",
  "Bredl's Python",
  "Briard",
  "British Timber",
  "Brittany",
  "Brontosaurus",
  "Bronze Whaler Shark",
  "Bronze-winged Jacana",
  "Brook Trout",
  "Brookesia Micra",
  "Brown Bear",
  "Brown Dog Tick",
  "Brown Headed Cowbird",
  "Brown Hyena",
  "Brown Snake",
  "Brown Tree Snake",
  "Brown Water Snake",
  "Brown-banded Cockroach",
  "Brug",
  "Brussels Griffon",
  "Budgerigar",
  "Buff Orpington Chicken",
  "Buffalo",
  "Buffalo Fish",
  "Bull and Terrier",
  "Bull Shark",
  "Bull Terrier",
  "Bull Trout",
  "Bullboxer",
  "Bulldog",
  "Bulldog Mix",
  "Bullfrog",
  "Bullmastiff",
  "Bullsnake",
  "Bumblebee",
  "Burmese",
  "Burmese Python",
  "Burrowing Frog",
  "Burrowing Owl",
  "Bush Baby",
  "Bush Dog",
  "Bush Viper",
  "Bushmaster Snake",
  "Butterfly",
  "Butterfly Fish",
  "Cabbage Moth",
  "Cactus Moth",
  "Cactus Mouse",
  "Cactus Wren",
  "Caecilian",
  "Caiman",
  "Caiman Lizard",
  "Cairn Terrier",
  "California Condor",
  "California Kingsnake",
  "California Tarantula",
  "Camel",
  "Camel Cricket",
  "Camel Spider",
  "Campine Chicken",
  "Canaan Dog",
  "Canada Lynx",
  "Canada Warbler",
  "Canadian Eskimo Dog",
  "Canadian Horse",
  "Cane Corso",
  "Cane Rat",
  "Cane Spider",
  "Cantil",
  "Canvasback",
  "Cape Lion",
  "Capuchin",
  "Capybara",
  "Caracal",
  "Cardinal",
  "Caribbean Reef Shark",
  "Caribou",
  "Carolina Dog",
  "Carolina Parakeet",
  "Carp",
  "Carpenter Ant",
  "Carpet Beetle",
  "Carpet Python",
  "Carpet Viper",
  "Carrion Beetle",
  "Cascabel",
  "Cashmere Goat",
  "Cassowary",
  "Cat",
  "Cat Snake",
  "Cat-Eyed Snake",
  "Cat-Faced Spider",
  "Catahoula Bulldog",
  "Catahoula Leopard",
  "Catalan Sheepdog",
  "Caterpillar",
  "Catfish",
  "Caucasian Mountain Dog",
  "Caucasian Shepherd",
  "Cava Tzu",
  "Cavador",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Cave Bear",
  "Cave Lion",
  "Cecropia Moth",
  "Cedar Waxwing",
  "Centipede",
  "Central Ranges Taipan",
  "Cephalaspis",
  "Ceratopsian",
  "Ceratosaurus",
  "Cervalces latifrons",
  "Cesky Fousek",
  "Cesky Terrier",
  "Chain Pickerel",
  "Chameleon",
  "Chamois",
  "Chartreux",
  "Cheagle",
  "Checkered Garter Snake",
  "Cheetah",
  "Chesapeake Bay Retriever",
  "Chestnut-Sided Warbler",
  "Chi Chi",
  "Chickadee",
  "Chicken",
  "Chicken Snake",
  "Chigger",
  "Chihuahua",
  "Chihuahua Mix",
  "Children's python",
  "Chilean Recluse Spider",
  "Chilean Rose Tarantula",
  "Chilesaurus",
  "Chimaera",
  "Chimpanzee",
  "Chinchilla",
  "Chinese Alligator",
  "Chinese Cobra",
  "Chinese Crested Dog",
  "Chinese Geese",
  "Chinese Paddlefish",
  "Chinese Shar-Pei",
  "Chinese Water Deer",
  "Chinook",
  "Chinook Salmon",
  "Chinstrap Penguin",
  "Chipit",
  "Chipmunk",
  "Chipoo",
  "Chipping Sparrow",
  "Chiton",
  "Chiweenie",
  "Chorkie",
  "Chow Chow",
  "Chow Pom",
  "Chow Shepherd",
  "Christmas Beetle",
  "Christmas Island Red Crab",
  "Chromodoris Willani",
  "Chusky",
  "Cicada",
  "Cichlid",
  "Cigarette Beetle",
  "Cinereous Vulture",
  "Cinnamon Ball Python",
  "Cinnamon Bear",
  "Cinnamon Ferret",
  "Clark's Grebe",
  "Clearnose Skate",
  "Click Beetle",
  "Clock Spider",
  "Clothes Moth",
  "Clouded Leopard",
  "Clownfish",
  "Clumber Spaniel",
  "Coachwhip Snake",
  "Coastal Carpet Python",
  "Coastal Taipan",
  "Coati",
  "Cobalt Blue Tarantula",
  "Cobia Fish",
  "Cobras",
  "Cochin Chicken",
  "Cockalier",
  "Cockapoo",
  "Cockatiel",
  "Cockatoo",
  "Cocker Spaniel",
  "Cockle",
  "Cockroach",
  "Coconut Crab",
  "Codfish",
  "Codling Moth",
  "Coelacanth",
  "Collared Peccary",
  "Collett's Snake",
  "Collie",
  "Collie Mix",
  "Colossal Squid",
  "Comb Jellyfish",
  "Comb-crested Jacana",
  "Comet Moth",
  "Comfort Retriever",
  "Common Buzzard",
  "Common Carp",
  "Common European Adder",
  "Common Frog",
  "Common Furniture Beetle",
  "Common Goldeneye",
  "Common Grackle",
  "Common Green Magpie",
  "Common House Spider",
  "Common Loon",
  "Common Raven",
  "Common Spotted Cuscus",
  "Common Toad",
  "Common Yellowthroat",
  "Compsognathus",
  "Cone Snail",
  "Conger Eel",
  "Congo Snake",
  "Conure",
  "Cookiecutter Shark",
  "Cooper's Hawk",
  "Copperhead",
  "Coral",
  "Coral Snake",
  "Corella",
  "Corgidor",
  "Corgipoo",
  "Corkie",
  "Corman Shepherd",
  "Cormorant",
  "Corn Earworm",
  "Corn Rex Cat",
  "Corn Snake",
  "Cory Catfish",
  "Coryphodon",
  "Cosmic Caterpillar",
  "Costa's Hummingbird",
  "Coton de Tulear",
  "Cotton-top Tamarin",
  "Cottonmouth",
  "Coues Deer",
  "Cougar",
  "Cow",
  "Cow Reticulated Python",
  "Coyote",
  "Crab",
  "Crab Spider",
  "Crab-Eating Fox",
  "Crab-Eating Macaque",
  "Crabeater Seal",
  "Crane",
  "Crappie Fish",
  "Crayfish",
  "Crested Gecko",
  "Crested Penguin",
  "Cricket",
  "Croatian Sheepdog",
  "Crocodile",
  "Crocodile Monitor",
  "Crocodile Shark",
  "Crocodylomorph",
  "Cross Fox",
  "Cross River Gorilla",
  "Crow",
  "Crucian Carp",
  "Cryolophosaurus",
  "Cuban Boa",
  "Cuban Cockroach",
  "Cubera Snapper",
  "Cuckoo",
  "Cucumber Beetle",
  "Curly Coated Retriever",
  "Curly Hair Tarantula",
  "Cuttlefish",
  "Czechoslovakian Wolfdog",
  "Dachsador",
  "Dachshund",
  "Dachshund Mix",
  "Daeodon",
  "Dalmadoodle",
  "Dalmador",
  "Dalmatian",
  "Dalmatian Mix",
  "Damselfish",
  "Dandie Dinmont Terrier",
  "Daniff",
  "Danios",
  "Danish Swedish Farmdog",
  "Dapple Dachshund",
  "Dark-Eyed Junco",
  "Dark-Eyed Junco",
  "Darkling Beetle",
  "Darwin's fox",
  "Darwin's Frog",
  "Daug",
  "De Brazza's Monkey",
  "De Kay's Brown Snake",
  "Death Adder",
  "Death's Head Cockroach",
  "Deathwatch Beetle",
  "Decorator Crab",
  "Deer",
  "Deer Head Chihuahua",
  "Deer Mouse",
  "Deer Tick",
  "Deinocheirus",
  "Deinosuchus",
  "Desert Ghost Ball Python",
  "Desert Kingsnake",
  "Desert Locust",
  "Desert Rain Frog",
  "Desert Tortoise",
  "Desert Wolf",
  "Desmostylus",
  "Deutsche Bracke",
  "Devil's Coach Horse Beetle",
  "Devon Rex",
  "Dhole",
  "Diamond Python",
  "Diamondback Moth",
  "Dickcissel",
  "Dickinsonia",
  "Dik-Dik",
  "Dilophosaurus",
  "Dimetrodon",
  "Diminutive Woodrat",
  "Dingo",
  "Dinocrocuta",
  "Dinofelis",
  "Dinopithecus",
  "Dinosaur Shrimp",
  "Dinosaurs",
  "Diplodocus",
  "Diprotodon",
  "Dire Wolf",
  "Disco Clam",
  "Discus",
  "Diving Bell Spider",
  "Diving Duck",
  "Doberman Pinscher",
  "Dobsonfly",
  "Dodo",
  "Doedicurus",
  "Dog",
  "Dog Tick",
  "Dogo Argentino",
  "Dogue De Bordeaux",
  "Dolphin",
  "Donkey",
  "Dorgi",
  "Dorkie",
  "Dorking Chicken",
  "Dormouse",
  "Double Doodle",
  "Douc",
  "Downy Woodpecker",
  "Doxiepoo",
  "Doxle",
  "Draco Volans Lizard",
  "Dragon Eel",
  "Dragon Snake",
  "Dragonfish",
  "Dragonfly",
  "Dreadnoughtus",
  "Drever",
  "Dried Fruit Moth",
  "Dromornis stirtoni",
  "Drum Fish",
  "Dubia Cockroach",
  "Duck",
  "Dugong",
  "Dumeril's Boa",
  "Dung Beetle",
  "Dungeness Crab",
  "Dunker",
  "Dunkleosteus",
  "Dunnock",
  "Dusky Dolphin",
  "Dusky Shark",
  "Dutch Rabbit",
  "Dutch Shepherd",
  "Dwarf Boa",
  "Dwarf Crocodile",
  "Dwarf Gourami",
  "Dwarf Hamster",
  "Eagle",
  "Eagle Ray",
  "Eared Grebe",
  "Earless Monitor Lizard",
  "Earthworm",
  "Earwig",
  "East Siberian Laika",
  "Eastern Barred Bandicoot",
  "Eastern Bluebird",
  "Eastern Box Turtle",
  "Eastern Brown Snake",
  "Eastern Chipmunk",
  "Eastern Coral Snake",
  "Eastern Cottontail",
  "Eastern Diamondback Rattlesnake",
  "Eastern Dobsonfly",
  "Eastern Fence Lizard",
  "Eastern Glass Lizard",
  "Eastern Gorilla",
  "Eastern Gray Squirrel",
  "Eastern Green Mamba",
  "Eastern Hognose Snake",
  "Eastern Indigo Snake",
  "Eastern Kingbird",
  "Eastern Lowland Gorilla",
  "Eastern Meadowlark",
  "Eastern Phoebe",
  "Eastern Racer",
  "Eastern Rat Snake",
  "Eastern Tiger Snake",
  "Eastern Turkey",
  "Eastern Woodrat",
  "Echidna",
  "Eclectus Parrot",
  "Edible Frog",
  "Eel",
  "Eel catfish",
  "Eelpout",
  "Egret",
  "Egyptian Cobra",
  "Egyptian Goose",
  "Egyptian Mau",
  "Egyptian Tortoise",
  "Egyptian Vulture",
  "Eider",
  "Eland",
  "Elasmosaurus",
  "Elasmotherium",
  "Electric Catfish",
  "Electric Eel",
  "Elegant Tern",
  "Elephant",
  "Elephant Beetle",
  "Elephant Bird",
  "Elephant Fish",
  "Elephant Seal",
  "Elephant Shrew",
  "Elf Owl",
  "Elk",
  "Ember Tetra",
  "Embolotherium",
  "Emerald Toucanet",
  "Emerald Tree Boa",
  "Emerald Tree Monitor",
  "Emperor Angelfish",
  "Emperor Goose",
  "Emperor Penguin",
  "Emperor Tamarin",
  "Emu",
  "Enchi Ball Python",
  "English Angora Rabbit",
  "English Bulldog",
  "English Cocker Spaniel",
  "English Cream Golden Retriever",
  "English Crested Guinea Pig",
  "English Foxhound",
  "English Longhorn Cattle",
  "English Pointer",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "English Toy Terrier",
  "Entlebucher Mountain Dog",
  "Epagneul Pont Audemer",
  "Epicyon haydeni",
  "Epidexipteryx",
  "Equatorial Spitting Cobra",
  "Equus giganteus",
  "Ermine",
  "Eryops",
  "Escolar",
  "Eskimo Dog",
  "Eskipoo",
  "Estrela Mountain Dog",
  "Euoplocephalus",
  "Eurasian Beaver",
  "Eurasian Bullfinch",
  "Eurasian Collared Dove",
  "Eurasian Eagle-owl",
  "Eurasian Jay",
  "Eurasian Lynx",
  "Eurasian Nuthatch",
  "Eurasian Sparrowhawk",
  "Eurasian Wolf",
  "Eurasier",
  "European Bee-Eater",
  "European Corn Borer",
  "European Goldfinch",
  "European Polecat",
  "European Robin",
  "European Starling",
  "European Wildcat",
  "Eurypterus",
  "Evening Bat",
  "Evening Grosbeak",
  "Executioner Wasp",
  "Eyelash Viper",
  "Fainting Goat",
  "Fairy-Wren",
  "Falcon",
  "Fallow deer",
  "False Cobra",
  "False coral snake",
  "False Killer Whale",
  "False Water Cobra",
  "False Widow Spider",
  "Fancy Mouse",
  "Fangtooth",
  "Feather Star",
  "Feist",
  "Fennec Fox",
  "Fer-de-lance Snake",
  "Ferret",
  "Ferruginous Hawk",
  "Fiddler Crab",
  "Field Cuckoo Bumblebee",
  "Field Spaniel",
  "Fierce Snake",
  "Figeater Beetle",
  "Fila Brasileiro",
  "Fin Whale",
  "Finch",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Fire Ball Python",
  "Fire Eel",
  "Fire Salamander",
  "Fire-Bellied Toad",
  "Firefly",
  "Firefly Ball Python",
  "Fish",
  "Fisher",
  "Fishing Cat",
  "Fishing Spiders",
  "Flamingo",
  "Flat-Coated Retriever",
  "Flathead Catfish",
  "Flea",
  "Flea Beetle",
  "Fleckvieh Cattle",
  "Florida Gar",
  "Florida Mouse",
  "Florida Panther",
  "Florida Woods Cockroach",
  "Flounder",
  "Flounder Fish",
  "Flour Beetle",
  "Flowerhorn Fish",
  "Fluke Fish",
  "Fly",
  "Flycatcher",
  "Flying Fish",
  "Flying Lemur",
  "Flying Snake",
  "Flying Squirrel",
  "Football Fish",
  "Forest Cobra",
  "Forest Cuckoo Bumblebee",
  "Formosan Mountain Dog",
  "Fossa",
  "Fox",
  "Fox Snakes",
  "Fox Squirrel",
  "Fox Terrier",
  "Freeway Ball Python",
  "French Bulldog",
  "French Bulldog Mix",
  "French Lop",
  "Frenchton",
  "Frengle",
  "Freshwater Crocodile",
  "Freshwater Drum",
  "Freshwater Eel",
  "Freshwater Jellyfish",
  "Freshwater Sunfish",
  "Frigatebird",
  "Frilled Lizard",
  "Frilled Shark",
  "Fritillary Butterfly",
  "Frizzle Chicken",
  "Frog",
  "Frogfish",
  "Frug",
  "Fruit Bat",
  "Fruit Fly",
  "Fulvous Whistling Duck",
  "Fur Seal",
  "Furrow Bee",
  "Gaboon Viper",
  "Gadwall",
  "Galapagos Penguin",
  "Galapagos Shark",
  "Galapagos Tortoise",
  "Gar",
  "Garden Eel",
  "Garden Spider",
  "Gargoyle Gecko",
  "Garter Snake",
  "Gastornis",
  "Gazelle",
  "Gecko",
  "Genet",
  "Gentoo Penguin",
  "Geoffroys Tamarin",
  "Gerberian Shepsky",
  "Gerbil",
  "German Cockroach",
  "German Longhaired Pointer",
  "German Pinscher",
  "German Shepherd Guide",
  "German Shepherd Mix",
  "German Sheppit",
  "German Sheprador",
  "German Shorthaired Pointer",
  "German Spitz",
  "German Wirehaired Pointer",
  "Gharial",
  "Ghost Catfish",
  "Ghost Crab",
  "Giant African Land Snail",
  "Giant Armadillo",
  "Giant Beaver",
  "Giant Clam",
  "Giant Desert Centipede",
  "Giant Golden Mole",
  "Giant House Spider",
  "Giant Isopod",
  "Giant Leopard Moth",
  "Giant Panda Bear",
  "Giant Salamander",
  "Giant Schnauzer",
  "Giant Schnoodle",
  "Giant Siphonophore",
  "Giant Trevally",
  "Giant Weta",
  "Giant Wood Moth",
  "Gibbon",
  "Gigantopithecus",
  "Gila Monster",
  "Giraffe",
  "Glass Frog",
  "Glass Lizard",
  "Glechon",
  "Glen Of Imaal Terrier",
  "Glowworm",
  "Gnat",
  "Goat",
  "Goberian",
  "Goblin Shark",
  "Goby Fish",
  "Goldador",
  "Goldcrest",
  "Golden Dox",
  "Golden Eagle",
  "Golden Irish",
  "Golden Jackal",
  "Golden Lancehead",
  "Golden Lion Tamarin",
  "Golden Masked Owl",
  "Golden Mole",
  "Golden Newfie",
  "Golden Oriole",
  "Golden Pyrenees",
  "Golden Retriever",
  "Golden Retriever Mix",
  "Golden Saint",
  "Golden Shepherd",
  "Golden Shiner",
  "Golden Tortoise Beetle",
  "Golden Trout",
  "Golden-Crowned Flying Fox",
  "Golden-Crowned Kinglet",
  "Goldendoodle",
  "Goldfish",
  "Goliath Beetle",
  "Goliath Frog",
  "Goliath Grouper",
  "Goliath Tigerfish",
  "Gollie",
  "Gomphotherium",
  "Goonch Catfish",
  "Goose",
  "Gooty Sapphire Tarantula",
  "Gopher",
  "Gopher Snake",
  "Gopher Tortoise",
  "Goral",
  "Gordon Setter",
  "Gorgosaurus",
  "Gorilla",
  "Goshawk",
  "Gouldian Finch",
  "Gourami",
  "Grapevine Beetle",
  "Grass Carp",
  "Grass Snake",
  "Grass Spider",
  "Grasshopper",
  "Grasshopper Mouse",
  "Gray Catbird",
  "Gray Fox",
  "Gray Tree Frog",
  "Great Blue Heron",
  "Great Crested Flycatcher",
  "Great Dane",
  "Great Dane Mix",
  "Great Danoodle",
  "Great Egret",
  "Great Hammerhead Shark",
  "Great Kiskadee",
  "Great Plains Rat Snake",
  "Great Potoo Bird",
  "Great Pyrenees",
  "Great Pyrenees Mix",
  "Great White Shark",
  "Greater Swiss Mountain Dog",
  "Grebe",
  "Green Anaconda",
  "Green Anole",
  "Green Aphids",
  "Green Bee-Eater",
  "Green Bottle Blue Tarantula",
  "Green Frog",
  "Green Heron",
  "Green June Beetle",
  "Green Mamba",
  "Green Rat Snake",
  "Green Snake",
  "Green Sunfish",
  "Green Tree Frog",
  "Green Tree Python",
  "Greenland Dog",
  "Greenland Shark",
  "Grey Heron",
  "Grey Mouse Lemur",
  "Grey Reef Shark",
  "Grey Seal",
  "Greyhound",
  "Griffon Vulture",
  "Griffonshire",
  "Grizzly Bear",
  "Groenendael",
  "Ground Snake",
  "Ground Squirrel",
  "Groundhog",
  "Groundhog Tick",
  "Grouper",
  "Grouse",
  "Grunion",
  "Guadalupe Bass",
  "Guinea Fowl",
  "Guinea Pig",
  "Gulper Catfish",
  "Gulper Eel",
  "Guppy",
  "Gypsy Cuckoo Bumblebee",
  "Gypsy Moth",
  "Gypsy Moth Caterpillar",
  "Haast's Eagle",
  "Habu Snake",
  "Haddock",
  "Hagfish",
  "Haikouichthys",
  "Hainosaurus",
  "Hairy Frogfish",
  "Hairy Woodpecker",
  "Hairy-footed Flower Bee",
  "Halibut",
  "Hallucigenia",
  "Hamburg Chicken",
  "Hammerhead Shark",
  "Hammerhead Worm",
  "Hammond's flycatcher",
  "Hamster",
  "Harbor Porpoise",
  "Harbor Seal",
  "Hardhead Catfish",
  "Hare",
  "Harlequin Coral Snake",
  "Harlequin Rabbit",
  "Harp Seal",
  "Harpy Eagle",
  "Harrier",
  "Harris's Hawk",
  "Hartebeest",
  "Hatzegopteryx",
  "Havamalt",
  "Havanese",
  "Havapoo",
  "Havashire",
  "Havashu",
  "Hawaiian Crow",
  "Hawaiian Goose",
  "Hawaiian Monk Seal",
  "Hawk",
  "Hawk Moth Caterpillar",
  "Hedgehog",
  "Helicoprion",
  "Hellbender",
  "Hepatic Tanager",
  "Hercules Beetle",
  "Hercules Moth",
  "Hermit Crab",
  "Heron",
  "Herrerasaurus",
  "Herring",
  "Herring Gull",
  "Highland Cattle",
  "Himalayan",
  "Hippopotamus",
  "Hippopotamus gorgops",
  "Hoary Bat",
  "Hobo Spider",
  "Hogfish",
  "Hognose snake",
  "Hokkaido",
  "Holy Cross Frog",
  "Honduran White Bat",
  "Honey Badger",
  "Honey Bee",
  "Honey Buzzard",
  "Hooded Oriole",
  "Hooded Seal",
  "Hook-Nosed Sea Snake",
  "Hoopoe",
  "Horgi",
  "Horn Shark",
  "Hornbill",
  "Horned Adder",
  "Horned Beetle",
  "Horned Grebe",
  "Horned Lizard",
  "Horned Viper",
  "Hornet",
  "Horse",
  "Horse Mackerel",
  "Horsefly",
  "Horseshoe Crab",
  "Houdan Chicken",
  "House Finch",
  "House Sparrow",
  "House wren",
  "Housefly",
  "Hovasaurus",
  "Hovawart",
  "Howler Monkey",
  //"Human",
  "Humboldt Penguin",
  "Humboldt Squid",
  "Hummingbird",
  "Hummingbird Hawk-Moth",
  "Humpback Whale",
  "Huntaway",
  "Huntsman Spider",
  "Huskador",
  "Huskita",
  "Husky",
  "Husky Jack",
  "Huskydoodle",
  "Hyacinth Macaw",
  "Hyaenodon",
  "Hyena",
  "Ibex",
  "Ibis",
  "Ibizan Hound",
  "Icadyptes",
  "Icelandic Sheepdog",
  "Ichthyosaurus",
  "Ichthyostega",
  "Iguana",
  "Iguanodon",
  "IMG Boa Constrictor",
  "Immortal Jellyfish",
  "Impala",
  "Imperial Moth",
  "Inchworm",
  "Indian Cobra",
  "Indian Elephant",
  "Indian Giant Squirrel",
  "Indian Palm Squirrel",
  "Indian python",
  "Indian Rhinoceros",
  "Indian Star Tortoise",
  "Indianmeal Moth",
  "Indigo Snake",
  "Indochinese Tiger",
  "Indri",
  "Inland Taipan",
  "Insect",
  "Insects",
  "Io Moth",
  "Irish Doodle",
  "Irish Elk",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish WolfHound",
  "Irukandji Jellyfish",
  "Italian Greyhound",
  "Ivory-billed woodpecker",
  "Ivy Bee",
  "Jabiru",
  "Jacana",
  "Jack Crevalle",
  "Jack Russells",
  "Jack-Chi",
  "Jackabee",
  "Jackal",
  "Jackdaw",
  "Jackrabbit",
  "Jackson's Chameleon",
  "Jagdterrier",
  "Jaguar",
  "Jaguarundi Cat",
  "Jamaican Boa",
  "Jamaican Iguana",
  "Japanese Bantam Chicken",
  "Japanese Beetle",
  "Japanese Chin",
  "Japanese Macaque",
  "Japanese rat snake",
  "Japanese Spitz",
  "Japanese Squirrel",
  "Japanese Terrier",
  "Javan Leopard",
  "Javan Rhinoceros",
  "Javanese",
  "Jellyfish",
  "Jerboa",
  "Jewel Beetle",
  "John Dory",
  "Jonah Crab",
  "Joro Spider",
  "Josephoartigasia monesi",
  "Jumping Spider",
  "Jungle Carpet Python",
  "Junglefowl",
  "Kagu",
  "Kai Ken",
  "Kakapo",
  "Kaluga Sturgeon",
  "Kamehameha Butterfly",
  "Kangal Shepherd Dog",
  "Kangaroo",
  "Kangaroo Mouse",
  "Kangaroo Rat",
  "Katydid",
  "Kaua'i",
  "Kea",
  "Keagle",
  "Keel-Billed Toucan",
  "Keelback",
  "Keeshond",
  "Kelp Greenling",
  "Kentucky Warbler",
  "Kenyan Sand Boa",
  "Kermode Bear",
  "Kerry Blue Terrier",
  "Kestrel",
  "Keta Salmon",
  "Key Deer",
  "Keyhole Cichlid",
  "Khao Manee",
  "Khapra Beetle",
  "Kiang",
  "Kiko Goat",
  "Killdeer",
  "Killer Clown Ball Python",
  "Killer Whale",
  "Killifish",
  "Kinabalu Giant Red Leech",
  "Kinder Goat",
  "King Cobra",
  "King Crab",
  "King Eider",
  "King Mackerel",
  "King Penguin",
  "King Quail",
  "King Rat Snake",
  "King Salmon",
  "King Shepherd",
  "King Snake",
  "King Vulture",
  "Kingfisher",
  "Kingklip",
  "Kinkajou",
  "Kirtland's Snake",
  "Kishu",
  "Kissing Bugs",
  "Kissing Gourami",
  "Kit Fox",
  "Kitefin Shark",
  "Kiwi",
  "Klipspringer",
  "Knifefish",
  "Knight Anole",
  "Koala",
  "Kodiak Bear",
  "Kodkod",
  "Koi Fish",
  "Kokanee Salmon",
  "Komodo Dragon",
  "Komondor",
  "Kooikerhondje",
  "Koolie",
  "Korean Jindo",
  "Kori Bustard",
  "Kouprey",
  "Kowari",
  "Krait",
  "Krill",
  "Kudu",
  "Kudzu Bug",
  "Kuvasz",
  "Labahoula",
  "Labmaraner",
  "Labout's Fairy Wrasse",
  "Labrabull",
  "Labradane",
  "Labradoodle",
  "Labrador Retriever",
  "Labraheeler",
  "Labrottie",
  "Lace Bug",
  "Lace Monitor",
  "Ladybug",
  "Ladyfish",
  "Lagotto Romagnolo",
  "Lake Sturgeon",
  "Lake Trout",
  "Lakeland Terrier",
  "LaMancha Goat",
  "Lamprey",
  "Lancashire Heeler",
  "Lancetfish",
  "Landseer Newfoundland",
  "Lappet-faced Vulture",
  "Lapponian Herder",
  "Larder Beetle",
  "Large Munsterlander",
  "Largemouth Bass",
  "Laughing Kookaburra",
  "Lavender Albino Ball Python",
  "Lawnmower Blenny",
  "Lazarus Lizard",
  "Leaf-Tailed Gecko",
  "Leafcutter Ant",
  "Leafcutter Bee",
  "Least Flycatcher",
  "Leatherback Sea Turtle",
  "Leech",
  "Leedsichthys",
  "Leghorn Chicken",
  "Leichhardt's Grasshopper",
  "Lemming",
  "Lemon Blast Ball Python",
  "Lemon Cuckoo Bumblebee",
  "Lemon Shark",
  "Lemur",
  "Leonberger",
  "Leopard",
  "Leopard Cat",
  "Leopard Frog",
  "Leopard Gecko",
  "Leopard Lizard",
  "Leopard Seal",
  "Leopard Shark",
  "Leopard Tortoise",
  "Leptocephalus",
  "Lesser Jacana",
  "Lesser Scaup",
  "Lhasa Apso",
  "Lhasapoo",
  "Liger",
  "Limpet",
  "Lineback Cattle",
  "Linnet",
  "Lion",
  "Lion's Mane Jellyfish",
  "Lionfish",
  "Liopleurodon",
  "Liopleurodon",
  "Lipstick Albino Boa",
  "Little Brown Bat",
  "Little Penguin",
  "Livyatan",
  "Lizard",
  "Lizardfish",
  "Llama",
  "Loach",
  "Lobster",
  "Locust",
  "Loggerhead Shrike",
  "Lone Star Tick",
  "Long-Eared Owl",
  "Long-Haired Rottweiler",
  "Long-Tailed Tit",
  "Long-Winged Kite Spider",
  "Longfin Mako Shark",
  "Longnose Gar",
  "Lorikeet",
  "Loris",
  "Lowchen",
  "Lumpfish",
  "Luna Moth",
  "Luna Moth Caterpillar",
  "Lungfish",
  "Lurcher",
  "Lykoi Cat",
  "Lynx",
  "Lyrebird",
  "Lystrosaurus",
  "Macaque",
  "Macaroni Penguin",
  "Macaw",
  "MacGillivray's Warbler",
  "Machaeroides",
  "Mackenzie Valley Wolf",
  "Macrauchenia",
  "Madagascar Hissing Cockroach",
  "Madagascar Jacana",
  "Madagascar Tree Boa",
  "Madora Moth",
  "Magellanic Penguin",
  "Maggot",
  "Magnolia Warbler",
  "Magpie",
  "Magyarosaurus",
  "Mahi Mahi",
  "Maiasaura",
  "Maine Coon",
  "Mal Shi",
  "Malayan Civet",
  "Malayan Krait",
  "Malayan Tiger",
  "Malchi",
  "Mallard",
  "Malteagle",
  "Maltese",
  "Maltese Mix",
  "Maltese Shih Tzu",
  "Maltipom",
  "Maltipoo",
  "Mamba",
  "Mamushi Snake",
  "Man of War Jellyfish",
  "Manatee",
  "Manchester Terrier",
  "Mandarin Rat Snake",
  "Mandrill",
  "Maned Wolf",
  "Mangrove Snake",
  "Mangrove Snapper",
  "Manta Ray",
  "Mantella Frog",
  "Marabou Stork",
  "Marans Chicken",
  "Marble Fox",
  "Maremma Sheepdog",
  "Margay",
  "Marine Iguana",
  "Marine Toad",
  "Markhor",
  "Marmoset",
  "Marmot",
  "Marsh Frog",
  "Marsican Brown Bear",
  "Masiakasaurus",
  "Masked Angelfish",
  "Masked Palm Civet",
  "Mason Bee",
  "Massasauga",
  "Mastador",
  "Mastiff",
  "Mastiff Mix",
  "Mauzer",
  "May Beetle",
  "Mayan Cichlid",
  "Mayfly",
  "Meagle",
  "Mealworm Beetle",
  "Mealybug",
  "Meerkat",
  "Megalania",
  "Megalochelys",
  "Megalodon",
  "Megamouth Shark",
  "Meganeura",
  "Megatherium",
  "Meiolania",
  "Mekong Giant Catfish",
  "Merganser",
  "Mexican Alligator Lizard",
  "Mexican Black Kingsnake",
  "Mexican Eagle",
  "Mexican Fireleg Tarantula",
  "Mexican Free-Tailed Bat",
  "Mexican Mole Lizard",
  "Microraptor",
  "Midget Faded Rattlesnake",
  "Miki",
  "Milk Snake",
  "Milkfish",
  "Milkweed aphids",
  "Millipede",
  "Mini Labradoodle",
  "Mini Lop",
  "Miniature Bull Terrier",
  "Miniature Husky",
  "Miniature Pinscher",
  "Mink",
  "Minke Whale",
  "Mississippi Kite",
  "Moccasin Snake",
  "Mockingbird",
  "Modern Game Chicken",
  "Mojarra",
  "Mojave Ball Python",
  "Mojave Rattlesnake",
  "Mola mola",
  "Mole",
  "Mole Crab",
  "Mole Cricket",
  "Mole Snake",
  "Mollusk",
  "Molly",
  "Monarch Butterfly",
  "Mongoose",
  "Mongrel",
  "Monitor Lizard",
  "Monkey",
  "Monkfish",
  "Monocled Cobra",
  "Monte Iberia Eleuth",
  "Moon Jellyfish",
  "Moonglow Boa",
  "Moorhen",
  "Moose",
  "Moray Eel",
  "Morkie",
  "Morpho Butterfly",
  "Mosasaurus",
  "Moscow Watchdog",
  "Mosquito",
  "Moth",
  "Mountain Beaver",
  "Mountain Bluebird",
  "Mountain Cur",
  "Mountain Feist",
  "Mountain Gorilla",
  "Mountain Lion",
  "Mourning Dove",
  "Mourning Gecko",
  "Mourning Warbler",
  "Mouse",
  "Mouse Spider",
  "Mouse-Deer",
  "Mozambique Spitting Cobra",
  "Mud Snake",
  "Mudi",
  "Mudpuppy",
  "Mudskipper",
  "Mule",
  "Mule Deer",
  "Mulga Snake",
  "Mullet Fish",
  "Muntjac",
  "Muscovy Duck",
  "Musk Deer",
  "Muskellunge",
  "Muskox",
  "Muskrat",
  "Mussurana Snake",
  "Muttaburrasaurus",
  "Muttaburrasaurus",
  "Myna Bird",
  "Nabarlek",
  "Naegleria",
  "Naked Mole Rat",
  "Narwhal",
  "Natterjack",
  "Nautilus",
  "Neanderthal",
  "Neapolitan Mastiff",
  "Nebelung",
  "Needlefish",
  "Nelore Cattle",
  "Nematode",
  "Neon Tetra",
  "Neptune Grouper",
  "Netherland Dwarf Rabbit",
  "New Hampshire Red Chicken",
  "Newfoundland",
  "Newfypoo",
  "Newt",
  "Nguni Cattle",
  "Nicobar pigeon",
  "Nigerian Goat",
  "Night Adder",
  "Night Heron",
  "Night Snake",
  "Nightingale",
  "Nightjar",
  "Nile Crocodile",
  "Nile Monitor",
  "Nile Perch",
  "Nilgai",
  "No See Ums",
  "Norfolk Terrier",
  "Norrbottenspets",
  "North American Black Bear",
  "Northern Alligator Lizard",
  "Northern Bobwhite",
  "Northern Cardinal",
  "Northern Flicker",
  "Northern Fur Seal",
  "Northern Harrier",
  "Northern Inuit Dog",
  "Northern Jacana",
  "Northern Parula",
  "Northern Pintail",
  "Northern Potoo",
  "Northern Screamer",
  "Northern Water Snake",
  "Norway Rat",
  "Norwegian Buhund",
  "Norwegian Elkhound",
  "Norwegian Forest",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Nose-Horned Viper",
  "Nova Scotia Duck Tolling Retriever",
  "Nubian Goat",
  "Nudibranch",
  "Numbat",
  "Nuralagus",
  "Nurse Shark",
  "Nut Weevil",
  "Nuthatch",
  "Nutria",
  "Nyala",
  "Oak Toad",
  "Oarfish",
  "Ocean Perch",
  "Ocean Pout",
  "Ocean Whitefish",
  "Oceanic Whitetip Shark",
  "Ocellated Turkey",
  "Ocelot",
  "Octopus",
  "Oenpelli python",
  "Oilfish",
  "Okapi",
  "Old English Sheepdog",
  "Old House Borer",
  "Oleander Hawk Moth",
  "Olingo",
  "Olive Baboon",
  "Olive python",
  "Olive Sea Snake",
  "Olm",
  "Olympic Marmot",
  "Onagadori Chicken",
  "Onager",
  "Opabinia",
  "Opah",
  "Opaleye",
  "Opossum",
  "Oranda Goldfish",
  "Orange Baboon Tarantula",
  "Orange Dream Ball Python",
  "Orange Roughy",
  "Orange Spider",
  "Orange Tanager",
  "Orange-Crowned Warbler",
  "Orangutan",
  "Orb Weaver",
  "Orchard Oriole",
  "Orchid Dottyback",
  "Oregon Spotted Frog",
  "Ori-Pei",
  "Oribi",
  "Oriental Cockroach",
  "Oriental Dwarf Kingfisher",
  "Orinoco Crocodile",
  "Ornate Bichir",
  "Ornate Black-Tailed Rattlesnake",
  "Ornate Box Turtle",
  "Ornithocheirus",
  "Ornithomimus",
  "Ortolan Bunting",
  "Oscar Fish",
  "Osprey",
  "Ostracod",
  "Ostrich",
  "Otter",
  "Otterhound",
  "Ovenbird",
  "Oviraptor",
  "Owl",
  "Owl Butterfly",
  "Owlfly",
  "Ox",
  "Oxpecker",
  "Oyster",
  "Oyster Toadfish",
  "Ozark Bass",
  "Pachycephalosaurus",
  "Pacific Coast Tick",
  "Pacific Sleeper Shark",
  "Pacific Spaghetti Eel",
  "Paddlefish",
  "Pademelon",
  "Painted Bunting",
  "Painted Turtle",
  "Palaeoloxodon namadicus",
  "Palaeophis",
  "Paleoparadoxia",
  "Palm Rat",
  "Palo Verde Beetle",
  "Panda Pied Ball Python",
  "Pangolin",
  "Pantaloon Bee",
  "Panther",
  "Panthera atrox",
  "Papillon",
  "Papillon Mix",
  "Paradise Flying Snake",
  "Parakeet",
  "Parasaurolophus",
  "Parrot",
  "Parrot Snake",
  "Parrotfish",
  "Parrotlet",
  "Parson Russell Terrier",
  "Parti Schnauzer",
  "Partridge",
  "Patagonian Cavy",
  "Patagonian Mara",
  "Patagotitan",
  "Patas Monkey",
  "Patterdale Terrier",
  "Pea Puffer",
  "Peacock",
  "Peacock Bass",
  "Peacock Butterfly",
  "Peacock Spider",
  "Peagle",
  "Peekapoo",
  "Pekingese",
  "Pelagornis",
  "Pelagornithidae",
  "Pelican",
  "Pelycosaurs",
  "Pembroke Welsh Corgi",
  "Penguin",
  "Pennsylvania Wood Cockroach",
  "Peppered Moth",
  "Peppermint Angelfish",
  "Perch Fish",
  "Pere David's Deer",
  "Peregrine Falcon",
  "Peringuey's Adder",
  "Perro De Presa Canario",
  "Persian",
  "Peruvian Guinea Pig",
  "Peruvian Inca Orchid",
  "Pesquet's Parrot",
  "Petit Basset Griffon Vendeen",
  "Petite Goldendoodle",
  "Pharaoh Hound",
  "Pheasant",
  "Pheasant-tailed Jacana",
  "Philippine Cobra",
  "Phoenix Chicken",
  "Phorusrhacos",
  "Phytosaurs",
  "Picardy Spaniel",
  "Pictus Catfish",
  "Piebald Dachshund",
  "Pied Ball Python",
  "Pied Tamarin",
  "Pied-Billed Grebe",
  "Pig",
  "Pig-Nosed Turtle",
  "Pigeon",
  "Pika",
  "Pike Fish",
  "Pileated Woodpecker",
  "Pinacate Beetle",
  "Pine Beetle",
  "Pine Marten",
  "Pine Siskin",
  "Pine Snake",
  "Pine Snake",
  "Pinfish",
  "Pink Bollworm",
  "Pink Fairy Armadillo",
  "Pink Salmon",
  "Pink Toed Tarantula",
  "Pink-Necked Green Pigeon",
  "Pipe Snake",
  "Pipefish",
  "Piranha",
  "Pit Bull",
  "Pit Viper",
  "Pitador",
  "Pitsky",
  "Plains Hognose Snake",
  "Platinum Arowana",
  "Platybelodon",
  "Platypus",
  "Plesiosaur",
  "Pliosaur",
  "Plott Hound Mix",
  "Plott Hounds",
  "Plymouth Rock Chicken",
  "Pocket Beagle",
  "Pocket Pitbull",
  "Podenco Canario",
  "Pointer",
  "Pointer Mix",
  "Poison Dart Frog",
  "Polacanthus",
  "Polar Bear",
  "Polecat",
  "Polish Chicken",
  "Polish Lowland Sheepdog",
  "Polish Tatra Sheepdog",
  "Polka Dot Stingray",
  "Pollock Fish",
  "Polyphemus Moth",
  "Pomapoo",
  "Pomchi",
  "Pomeagle",
  "Pomeranian",
  "Pomeranian Mix",
  "Pompano Fish",
  "Pomsky",
  "Pond Skater",
  "Poochon",
  "Poodle",
  "Poogle",
  "Pool Frog",
  "Porbeagle Shark",
  "Porcupine",
  "Porcupinefish",
  "Portuguese Podengo",
  "Possum",
  "Potato Beetle",
  "Potoo",
  "Potoroo",
  "Powderpost Beetle",
  "Prairie Chicken",
  "Prairie Dog",
  "Prairie Rattlesnake",
  "Prawn",
  "Praying Mantis",
  "Proboscis Monkey",
  "Procoptodon",
  "Pronghorn",
  "Psittacosaurus",
  "Psittacosaurus",
  "Pteranodon",
  "Pterodactyl",
  "Pudelpointer",
  "Puertasaurus",
  "Puff Adder",
  "Pufferfish",
  "Puffin",
  "Pug",
  "Pug Mix",
  "Pugapoo",
  "Puggle",
  "Pugshire",
  "Puli",
  "Puma",
  "Pumi",
  "Pumpkin Patch Tarantula",
  "Purple Emperor Butterfly",
  "Purple Finch",
  "Purple Gallinule",
  "Purple Tarantula",
  "Purussaurus",
  "Puss Caterpillar",
  "Puss Moth",
  "Pygmy Hippopotamus",
  "Pygmy Marmoset",
  "Pygmy python",
  "Pygmy Rattlesnake",
  "Pygmy Shark",
  "Pygora Goat",
  "Pyjama Shark",
  "Pyrador",
  "Pyredoodle",
  "Pyrenean Mastiff",
  "Pyrenean Shepherd",
  "Pyrosome",
  "Python",
  "Quagga",
  "Quahog Clam",
  "Quail",
  "Queen Snake",
  "Quetzal",
  "Quetzalcoatlus northropi",
  "Quokka",
  "Quoll",
  "Rabbit",
  "Raccoon",
  "Raccoon Dog",
  "Racer Snake",
  "Radiated Tortoise",
  "Ragamuffin",
  "Ragdoll",
  "Raggle",
  "Rainbow Boa",
  "Rainbow Grasshopper",
  "Rainbow Kribs",
  "Rainbow Shark",
  "Rat",
  "Rat Snakes",
  "Rat Terrier",
  "Rattlesnake",
  "Red Ackie Monitor",
  "Red Aphids",
  "Red Deer",
  "Red Diamondback Rattlesnake",
  "Red Drum Fish",
  "Red Finch",
  "Red Fox",
  "Red Kite",
  "Red Knee Tarantula",
  "Red Nose Pit Bull",
  "Red Panda",
  "Red Paper Wasp",
  "Red Racer Snake",
  "Red Spitting Cobra",
  "Red Squirrel",
  "Red Star Chicken",
  "Red Tail Boa",
  "Red Wolf",
  "Red-Bellied Black Snake",
  "Red-Bellied Woodpecker",
  "Red-Billed Quelea Bird",
  "Red-Eared Slider",
  "Red-Eyed Tree Frog",
  "Red-Footed Tortoise",
  "Red-handed Tamarin",
  "Red-Headed Vulture",
  "Red-Lipped Batfish",
  "Red-Shouldered Hawk",
  "Red-Tailed Cuckoo Bumblebee",
  "Red-winged blackbird",
  "Redback Spider",
  "Redbone Coonhound",
  "Redcap Chicken",
  "Redear Sunfish",
  "Redhump Eartheater",
  "Redstart",
  "Redtail Catfish",
  "Reef Shark",
  "Regal Jumping Spider",
  "Reindeer",
  "Repenomamus",
  "Reticulated python",
  "Rex Rabbit",
  "Rhamphosuchus",
  "Rhea",
  "Rhesus Macaque",
  "Rhino Beetle",
  "Rhino Viper",
  "Rhinoceros",
  "Rhode Island Red Chicken",
  "Rhodesian Ridgeback",
  "Rhombic Egg-Eater Snake",
  "Ribbon Eel",
  "Ribbon Snake",
  "Rim Rock Crowned Snake",
  "Ring-billed Gull",
  "Ringed Kingfisher",
  "Rinkhals Snake",
  "River Otter",
  "River Turtle",
  "Roadrunner",
  "Robber Flies",
  "Robin",
  "Rock Bass",
  "Rock Crab",
  "Rock Hyrax",
  "Rock Python",
  "Rockfish",
  "Rockhopper Penguin",
  "Rodents",
  "Roe Deer",
  "Roosevelt Elk",
  "Rooster",
  "Root Aphids",
  "Rose-Breasted Grosbeak",
  "Roseate Spoonbill",
  "Rosy Boa",
  "Rotterman",
  "Rottle",
  "Rottsky",
  "Rottweiler",
  "Rottweiler Mix",
  "Rough Earth Snake",
  "Rough Green Snake",
  "Rough-Legged Hawk",
  "Rove Beetle",
  "Royal Penguin",
  "Rubber Boa",
  "Ruby-Crowned Kinglet",
  "Ruby-Throated Hummingbird",
  "Ruddy Duck",
  "Ruddy Turnstone",
  "Rufous Hummingbird",
  "Russel's Viper",
  "Russell Terrier",
  "Russian Bear Dog",
  "Russian Blue",
  "Russian Tortoise",
  "Saanen Goat",
  "Saarloos Wolfdog",
  "Saber-Toothed Tiger",
  "Sable",
  "Sable Black German Shepherd",
  "Sable Ferret",
  "Sable German Shepherd",
  "Saddleback Caterpillar",
  "Saiga",
  "Sailfish",
  "Saint Berdoodle",
  "Saint Bernard",
  "Saint Shepherd",
  "Salamander",
  "Salmon",
  "Salmon Shark",
  "Saluki",
  "Sambar",
  "Samoyed",
  "San Francisco Garter Snake",
  "Sand Cat",
  "Sand Crab",
  "Sand Dollar",
  "Sand Lizard",
  "Sand Tiger Shark",
  "Sand Viper",
  "Sandhill Crane",
  "Sandpiper",
  "Sandworm",
  "Saola",
  "Sapsali",
  "Sarcosuchus",
  "Sardines",
  "Sarkastodon",
  "Sarplaninac",
  "Sarus Crane",
  "Satanic Leaf-Tailed Gecko",
  "Saturniidae Moth",
  "Sauropoda",
  "Sauropoda",
  "Savanna Goat",
  "Savannah Monitor",
  "Savannah Sparrow",
  "Savu Python",
  "Saw-scaled Viper",
  "Sawfish",
  "Scale-Crested Pygmy Tyrant",
  "Scaleless Ball Python",
  "Scallops",
  "Scarab Beetle",
  "Scarlet Kingsnake",
  "Scarlet Macaw",
  "Scarlet Tanager",
  "Schapendoes",
  "Schipperke",
  "Schneagle",
  "Schnoodle",
  "Scimitar-horned Oryx",
  "Scissor-tailed Flycatcher",
  "Scorpion",
  "Scorpion Fish",
  "Scotch Collie",
  "Scottish Deerhound",
  "Scottish Fold Cat",
  "Scottish Terrier",
  "Scrotum Frog",
  "Sculpin",
  "Scutosaurus",
  "Sea Anemone",
  "Sea Bass",
  "Sea Dragon",
  "Sea Eagle",
  "Sea Lion",
  "Sea Otter",
  "Sea Roach",
  "Sea Slug",
  "Sea Snake",
  "Sea Spider",
  "Sea Squirt",
  "Sea Trout",
  "Sea Turtle",
  "Sea Urchin",
  "Seagull",
  "Seahorse",
  "Seal",
  "Sealyham Terrier",
  "Sedge Warbler",
  "Sehuencas Water Frog",
  "Sei Whale",
  "Senegal Parrot",
  "Senepol Cattle",
  "Sequined Spider",
  "Serval",
  "Seymouria",
  "Shantungosaurus",
  "Shark",
  "Sharp-Shinned Hawk",
  "Sharp-Tailed Snake",
  "Shastasaurus",
  "Sheep",
  "Sheepadoodle",
  "Sheepshead Fish",
  "Shepadoodle",
  "Shepkita",
  "Shepweiler",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shiba Inu Mix",
  "Shichi",
  "Shih Poo",
  "Shih Tzu",
  "Shih Tzu Mix",
  "Shikoku",
  "Shiloh Shepherd",
  "Shiranian",
  "Shoebill Stork",
  "Shollie",
  "Short-Eared Owl",
  "Short-Faced Bear",
  "Shortfin Mako Shark",
  "Shrew",
  "Shrimp",
  "Siamese",
  "Siberian",
  "Siberian Husky",
  "Siberian Ibex",
  "Siberian Retriever",
  "Siberian Tiger",
  "Siberpoo",
  "Sichuan Takin",
  "Sidewinder",
  "Sika Deer",
  "Silken Windhound",
  "Silkie Chicken",
  "Silky Shark",
  "Silky Terrier",
  "Silver Dollar",
  "Silver Labrador",
  "Simbakubwa",
  "Sinosauropteryx",
  "Sivatherium",
  "Six-Eyed Sand Spiders",
  "Sixgill shark",
  "Skate Fish",
  "Skeleton Tarantula",
  "Skink Lizard",
  "Skipjack Tuna",
  "Skua",
  "Skunk",
  "Skye Terrier",
  "Sleeper Shark",
  "Sloth",
  "Slovak Cuvac",
  "Slow Worm",
  "Slug",
  "Smallmouth Bass",
  "Smilosuchus",
  "Smokybrown Cockroach",
  "Smooth Earth Snake",
  "Smooth Fox Terrier",
  "Smooth Green Snake",
  "Smooth Hammerhead Shark",
  "Smooth Snake",
  "Snail",
  "Snailfish",
  "Snake",
  "Snapping Turtle",
  "Snook Fish",
  "Snorkie",
  "Snouted Cobra",
  "Snow Bunting",
  "Snow Crab",
  "Snow Goose",
  "Snow Leopard",
  "Snowberry Clearwing Moth",
  "Snowflake Eel",
  "Snowshoe",
  "Snowshoe Hare",
  "Snowy Owl",
  "Sockeye Salmon",
  "Soldier Beetle",
  "Somali",
  "Song Sparrow",
  "Song Thrush",
  "South China Tiger",
  "Southeastern Blueberry Bee",
  "Southern Black Racer",
  "Southern Flannel Moth",
  "Southern Hognose Snake",
  "Southern House Spider",
  "Southern Pacific Rattlesnake",
  "Spadefoot Toad",
  "Spalax",
  "Spanador",
  "Spanish Goat",
  "Spanish Mackerel",
  "Spanish Mastiff",
  "Spanish Water Dog",
  "Sparrow",
  "Sparrowhawk",
  "Speckled Kingsnake",
  "Speckled Trout",
  "Spectacled Bear",
  "Sperm Whale",
  "Sphynx",
  "Spider",
  "Spider Ball Python",
  "Spider Beetle",
  "Spider Monkey",
  "Spider Wasp",
  "Spider-Tailed Horned Viper",
  "Spinner Shark",
  "Spinone Italiano",
  "Spinosaurus",
  "Spiny bush viper",
  "Spiny Dogfish",
  "Spiny Hill Turtle",
  "Spitting Cobra",
  "Spixs Macaw",
  "Sponge",
  "Spongy Moth",
  "Spongy Moth",
  "Spotted Bass",
  "Spotted Gar",
  "Spotted Garden Eel",
  "Spotted Lanternfly",
  "Spotted python",
  "Spotted Skunk",
  "Springador",
  "Springbok",
  "Springerdoodle",
  "Squash Bee",
  "Squash Beetle",
  "Squid",
  "Squirrel",
  "Squirrel Monkey",
  "Squirrelfish",
  "Sri Lankan Elephant",
  "Stabyhoun",
  "Staffordshire Bull Terrier",
  "Stag Beetle",
  "Standard Schnauzer",
  "Star-nosed mole",
  "Starfish",
  "Stargazer Fish",
  "Steelhead Salmon",
  "Steller's Sea Cow",
  "Stick Insect",
  "Stiletto Snake",
  "Stingray",
  "Stoat",
  "Stone Crab",
  "Stonechat",
  "Stonefish",
  "Stoplight Loosejaw",
  "Stork",
  "Strawberry Hermit Crab",
  "Striped Bass",
  "Striped Hyena",
  "Striped Rocket Frog",
  "Stromatolite",
  "Stupendemys",
  "Sturgeon",
  "Styracosaurus",
  "Suchomimus",
  "Suckerfish",
  "Sugar Glider",
  "Sulcata Tortoise",
  "Sultan Chicken",
  "Sumatran Elephant",
  "Sumatran Orangutan",
  "Sumatran Rhinoceros",
  "Sumatran Tiger",
  "Summer Tanager",
  "Sun Bear",
  "Sunbeam Snake",
  "Sunset Ball Python",
  "Super Pastel Ball Python",
  "Supersaurus",
  "Superworm",
  "Surgeonfish",
  "Sussex Chicken",
  "Swai Fish",
  "Swainson's Hawk",
  "Swallow",
  "Swallowtail Butterfly",
  "Swallowtail Caterpillar",
  "Swan",
  "Swedish Elkhound",
  "Swedish Lapphund",
  "Swedish Vallhund",
  "Swordfish",
  "Syrian Hamster",
  "Taco Terrier",
  "Tailless Whip Scorpion",
  "Taimen Fish",
  "Taipan",
  "Takin",
  "Tamarin",
  "Tamaskan",
  "Tang",
  "Tangerine Leopard Gecko",
  "Tapanuli Orangutan",
  "Tapir",
  "Tarantula",
  "Tarantula Hawk",
  "Tarbosaurus",
  "Tarpon",
  "Tarsier",
  "Tasmanian Devil",
  "Tasmanian Tiger",
  "Tasmanian Tiger Snake",
  "Tawny Frogmouth",
  "Tawny Mining Bee",
  "Tawny Owl",
  "Teacup Chihuahua",
  "Teacup Maltese",
  "Teacup Miniature Horse",
  "Teacup Poodle",
  "Teddy Bear Hamster",
  "Teddy Guinea Pig",
  "Teddy Roosevelt Terrier",
  "Telescope Fish",
  "Ten-Lined June Beetle",
  "Tennessee Walking Horse",
  "Tenrec",
  "Tent Caterpillar",
  "Tentacled Snake",
  "Tenterfield Terrier",
  "Termite",
  "Terrier",
  "Terror Bird",
  "Tetra",
  "Texas Blind Snake",
  "Texas Brown Tarantula",
  "Texas Coral Snake",
  "Texas Garter Snake",
  "Texas Heeler",
  "Texas Indigo Snake",
  "Texas Night Snake",
  "Texas Rat Snake",
  "Texas Spiny Lizard",
  "Thai Ridgeback",
  "Thalassomedon",
  "Thanatosdrakon",
  "Therizinosaurus",
  "Theropod",
  "Thornback Ray",
  "Thorny Devil",
  "Thresher Shark",
  "Thrush",
  "Thylacoleo",
  "Thylacoleo carnifex",
  "Thylacosmilus",
  "Tibetan Fox",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Tick",
  "Tiffany",
  "Tiger",
  "Tiger Beetle",
  "Tiger Moth",
  "Tiger Muskellunge",
  "Tiger Rattlesnake",
  "Tiger Salamander",
  "Tiger Shark",
  "Tiger snake",
  "Tiger Swallowtail",
  "Tiger Swallowtail Caterpillar",
  "Tiger Trout",
  "Tiktaalik",
  "Timber Rattlesnake",
  "Timor python",
  "Tire Track Eel",
  "Titan Beetle",
  "Titanoboa",
  "Titanosaur",
  "Toadfish",
  "Tokay Gecko",
  "Tomato Hornworm",
  "Torkie",
  "Tornjak",
  "Tortoise",
  "Tosa",
  "Toucan",
  "Towhee",
  "Toxodon",
  "Toy Fox Terrier",
  "Toy Poodle",
  "Transylvanian Hound",
  "Trapdoor spider",
  "Tree Cricket",
  "Tree Frog",
  "Tree Kangaroo",
  "Tree Snake",
  "Tree swallow",
  "Tree Viper",
  "Treecreeper",
  "Treehopper",
  "Treeing Tennessee Brindle",
  "Treeing Walker Coonhound",
  "Triggerfish",
  "Troodon",
  "Tropicbird",
  "Trout",
  "Tsetse Fly",
  "Tuatara",
  "Tufted Coquette",
  "Tufted Titmouse",
  "Tully Monster",
  "Tuna",
  "Tundra Swan",
  "Turaco",
  "Turkey",
  "Turkey Vulture",
  "Turkish Angora",
  "Turnspit",
  "Turtle Frog",
  "Turtles",
  "Tusoteuthis",
  "Tussock Moth",
  "Tussock Moth Caterpillar",
  "Twig Snake",
  "Tylosaurus",
  "Tyrannosaurus Rex",
  "Uakari",
  "Uaru Cichlid",
  "Uguisu",
  "Uinta Ground Squirrel",
  "Uintatherium",
  "Ulysses Butterfly",
  "Umbrellabird",
  "Unau",
  "Underwing Moth",
  "Upland Sandpiper",
  "Ural owl",
  "Urechis unicinctus",
  "Urial",
  "Uromastyx",
  "Urutu Snake",
  "Utonagan",
  "Valley Bulldog",
  "Vampire Bat",
  "Vampire Crab",
  "Vampire Squid",
  "Vaquita",
  "Veery",
  "Vegavis",
  "Velociraptor",
  "Venus Flytrap",
  "Vermilion Flycatcher",
  "Vervet Monkey",
  "Vestal Cuckoo Bumblebee",
  "Vicuna",
  "Vine Snake",
  "Vinegaroon",
  "Viper",
  "Viper Boa",
  "Viper Shark",
  "Viperfish",
  "Virgin Islands Dwarf Gecko",
  "Vizsla",
  "Volcano Snail",
  "Vole",
  "Volpino Italiano",
  "Vulture",
  "Wahoo Fish",
  "Waimanu",
  "Walking Catfish",
  "Wallaby",
  "Walleye Fish",
  "Walrus",
  "Wandering Albatross",
  "Warbler",
  "Warthog",
  "Wasp",
  "Water Beetle",
  "Water Buffalo",
  "Water Bug",
  "Water Dragon",
  "Water Vole",
  "Waterbuck",
  "Wattled Jacana",
  "Wax Moth",
  "Weasel",
  "Weaver Bird",
  "Weimaraner",
  "Weimardoodle",
  "Wels Catfish",
  "Welsh Black Cattle",
  "Welsh Corgi",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland Terrier",
  "West Siberian Laika",
  "Western Blacklegged Tick",
  "Western Blind Snake",
  "Western Diamondback Rattlesnake",
  "Western Gorilla",
  "Western Green Mamba",
  "Western Hognose Snake",
  "Western Kingbird",
  "Western Lowland Gorilla",
  "Western Rat Snake",
  "Western Rattlesnake",
  "Western Tanager",
  "Westiepoo",
  "Whale Shark",
  "Wheaten Terrier",
  "Whimbrel",
  "Whinchat",
  "Whippet",
  "Whiptail Lizard",
  "White Bass",
  "White Butterfly",
  "White Catfish",
  "White Crappie",
  "White Ferret",
  "White German Shepherd",
  "White Marlin",
  "White Rhinoceros",
  "White Shark",
  "White Sturgeon",
  "White Tiger",
  "White-Crowned Sparrow",
  "White-Eyed Vireo",
  "White-Faced Capuchin",
  "White-shouldered House Moth",
  "White-tail deer",
  "White-Tailed Eagle",
  "Whitetail Deer",
  "Whiting",
  "Whoodle",
  "Whooping Crane",
  "Wild Boar",
  "Wildebeest",
  "Willow Flycatcher",
  "Willow Warbler",
  "Winter Moth",
  "Wire Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Wirehaired Vizsla",
  "Wiwaxia",
  "Wolf",
  "Wolf Eel",
  "Wolf Snake",
  "Wolf Spider",
  "Wolffish",
  "Wolverine",
  "Woma Python",
  "Wombat",
  "Wood Bison",
  "Wood Duck",
  "Wood Frog",
  "Wood Tick",
  "Wood Turtle",
  "Woodlouse",
  "Woodlouse Spider",
  "Woodpecker",
  "Woodrat",
  "Wool Carder Bee",
  "Woolly Aphids",
  "Woolly Bear Caterpillar",
  "Woolly Mammoth",
  "Woolly Monkey",
  "Woolly Rhinoceros",
  "Worm",
  "Worm Snake",
  "Wrasse",
  "Writing Spider",
  "Wrought Iron Butterflyfish",
  "Wryneck",
  "Wyandotte Chicken",
  "Wyoming Toad",
  "X-Ray Tetra",
  "Xeme",
  "Xenacanthus",
  "Xenoceratops",
  "Xenoposeidon",
  "Xenotarsosaurus",
  "Xerus",
  "Xiaosaurus",
  "Xiaotingia",
  "Xingu River Ray",
  "Xiongguanlong",
  "Xiphactinus",
  "Xoloitzcuintli",
  "Yabby",
  "Yak",
  "Yakutian Laika",
  "Yarara",
  "Yellow Anaconda",
  "Yellow Aphids",
  "Yellow Bass",
  "Yellow Bellied Sapsucker",
  "Yellow Belly Ball Python",
  "Yellow Bullhead Catfish",
  "Yellow Cobra",
  "Yellow Crazy Ant",
  "Yellow Perch",
  "Yellow Sac Spider",
  "Yellow Spotted Lizard",
  "Yellow Tanager",
  "Yellow Tang",
  "Yellow-Bellied Sea Snake",
  "Yellow-Eyed Penguin",
  "Yellow-faced Bee",
  "Yellowfin Tuna",
  "Yellowhammer",
  "Yellowish Cuckoo Bumblebee",
  "Yellowjacket",
  "Yellowtail Snapper",
  "Yellowthroat",
  "Yeti Crab",
  "Yokohama Chicken",
  "Yoranian",
  "Yorkie Bichon",
  "Yorkiepoo",
  "Yorkshire Terrier",
  "Zebra",
  "Zebra Finch",
  "Zebra Mussels",
  "Zebra Pleco",
  "Zebra Shark",
  "Zebra Snake",
  "Zebra Spitting Cobra",
  "Zebra Tarantula",
  "Zebrafish",
  "Zebu",
  "Zokor",
  "Zonkey",
  "Zorse",
  "Zuchon"
];

const genderList = [
  "girl",
  "boy"
  //look i'm just preparing to scale this
];

//list is from https://en.wikipedia.org/wiki/List_of_organs_of_the_human_body
const partList = [
  //"Human skeleton",
  "Joints",
  "Ligaments",
  "Muscles",
  "Tendons",
  "Teeth",
  "Tongue",
  "Lips",
  "Parotid glands",
  "Submandibular glands",
  "Sublingual glands",
  "Pharynx",
  "Esophagus",
  "Stomach",
  "Duodenum",
  "Jejunum",
  "Ileum",
  "Cecum",
  //"Ascending colon",
  //"Transverse colon",
  //"Descending colon",
  //"Sigmoid colon",
  "Colon",
  "Rectum",
  "Liver",
  "Gallbladder",
  "Mesentery",
  "Pancreas",
  "Anal canal",
  "Nasal cavity",
  "Pharynx",
  "Larynx",
  "Trachea",
  "Bronchi",
  "Bronchioles",
  "Lungs",
  //"Muscles of breathing",
  "Kidneys",
  "Ureter",
  "Bladder",
  "Urethra",
  "Ovaries",
  "Fallopian tubes",
  "Uterus",
  "Cervix",
  "Placenta",
  "Vulva",
  "Clitoris",
  "Vagina",
  "Testicles",
  "Epididymides",
  "Vasa deferentia",
  "Seminal vesicles",
  "Prostate",
  "Bulbourethral glands",
  "Penis",
  "Scrotum",
  "Pituitary gland",
  "Pineal gland",
  "Thyroid gland",
  "Parathyroid glands",
  "Adrenal glands",
  "Pancreas",
  "Heart",
  "Arteries",
  "Veins",
  "Capillaries",
  "Lymphatic vessel",
  "Lymph node",
  "Bone marrow",
  "Thymus",
  "Spleen",
  "Tonsils",
  "Interstitium",
  "Cerebral hemispheres",
  "Thalamus",
  "Hypothalamus",
  "Midbrain",
  "Cerebellum",
  "Pons",
  "Medulla oblongata",
  "Spinal cord",
  "Choroid plexus",
  "Cranial nerves",
  "Spinal nerves",
  "Ganglia",
  //"Enteric nervous system",
  "Cornea",
  "Iris",
  "Ciliary body",
  "Lens",
  "Retina",
  "Earlobe",
  "Eardrum",
  "Ossicles",
  "Cochlea",
  "Ear vestibule",
  "Semicircular canals",
  "Olfactory epithelium",
  "Taste buds",
  "Mammary glands",
  "Skin",
  "Subcutaneous tissue"
];

//list is from https://en.wikipedia.org/wiki/List_of_bones_of_the_human_skeleton
const boneList = [
  //"Cranial bones",
  "Occipital bone",
  //"Parietal bones",
  "Frontal bone",
  //"Temporal bones",
  //"Sphenoid bone",
  "Ethmoid bone",
  //"Facial bones",
  //"Nasal bones",
  "Maxilla",
  "Lacrimal bone",
  "Zygomatic bone",
  "Palatine bone",
  "Inferior nasal concha",
  "Vomer",
  "Hyoid bone",
  "Mandible",
  "Middle ears",
  "Malleus",
  "Incus",
  "Stapes",
  "Sternum",
  "Ribs",
  "Cervical ribs",
  "Cervical vertebrae",
  "Thoracic vertebrae",
  "Lumbar vertebrae",
  "Sacrum",
  "Coccyx",
  "hip bone",
  "Ilium",
  "Ischium",
  "Pubis",
  "Sacrum",
  "Coccyx",
  "Humerus",
  "Pectoral girdle",
  "Scapula",
  "Clavicle",
  "Ulna",
  "Radius",
  "Hand",
  "Carpals",
  "Scaphoid bone",
  "Lunate bone",
  "Triquetral bone",
  "Pisiform bone",
  "Trapezium",
  "Trapezoid bone",
  "Capitate bone",
  "Hamate bone",
  "Metacarpals",
  "Hand phalanges",
  "Proximal phalanges",
  "Intermediate phalanges",
  "Distal phalanges",
  "Femur",
  "Patella",
  "Tibia",
  "Fibula",
  "Foot",
  "Tarsus",
  "Calcaneus",
  "Talus",
  "Navicular bone",
  "Medial cuneiform bone",
  "Intermediate cuneiform bone",
  "Lateral cuneiform bone",
  "Cuboid bone",
  "Metatarsals",
  "Foot phalanges",
  "Proximal phalanges",
  "Intermediate phalanges",
  "Distal phalanges"
];

//list is from https://en.wiktionary.org/wiki/Thesaurus:penis
const penisList = [
  "anaconda",
  "baloney pony",
  "bald-headed hermit",
  "banana",
  "birdie",
  "bobby",
  "boonga",
  //"boy",
  "cack",
  "choad",
  "choda",
  "chode",
  "chopper",
  "cigar",
  "cock",
  "corey",
  "crank",
  "custard launcher",
  "D",
  "dick",
  "dicklet",
  "diddle",
  "diddly",
  "dingaling",
  "ding-a-ling",
  "ding-dong",
  "dinger",
  "dingle",
  "dingus",
  "dingy",
  "dink",
  "dinkle",
  "dipstick",
  "dirk",
  "disco stick",
  "dog bone",
  "dong",
  "donger",
  "Donkey Kong",
  "doodle",
  "dork",
  "down",
  "fire hose",
  "fuckpole",
  "gherkin",
  "hairy canary",
  "hammer",
  "hog",
  "hot dog",
  "hot rod",
  "hoo-hoo",
  "hooter",
  "it",
  "jade stalk",
  "jamoke",
  "jigger",
  "jimmy",
  "jock",
  "johnson",
  "John Thomas",
  "joint",
  "jonathan",
  "joystick",
  "kielbasa",
  "knob",
  "lad",
  "langer",
  "lingam",
  "love muscle",
  "love stick",
  "love truncheon",
  "love sausage",
  "love wand",
  "machine",
  "magnum",
  "Master John Goodfellow",
  "male member",
  "manhood",
  "man-meat",
  "meat",
  "meat puppet",
  "meat rod",
  "meat scepter",
  "meatstick",
  "meat stick",
  "member",
  "membrum virile",
  "nature's scythe",
  "nob",
  "old chap",
  "old fellow",
  "one-eyed trouser snake",
  "organ",
  "package",
  "pecker",
  "peen",
  "pee-pee",
  "pee-wee",
  "pego",
  "penis",
  "peter",
  "phallus",
  "pickle",
  "piece",
  "piece of pork",
  "pike",
  "pingas",
  "pink cigar",
  "pink oboe",
  "pintle",
  "pipe",
  "pisser",
  "piston",
  "pizzle",
  "plonker",
  "pork sword",
  "prick",
  "pud",
  "purple-headed yogurt slinger",
  "putz",
  "p-word",
  "python",
  "ramrod",
  //"rape tool",
  "rod",
  "root",
  "rutter",
  "salami",
  "sausage",
  "schlong",
  "schmuck",
  "sex tool",
  "shaft",
  "shlong",
  "shmekl",
  "short arm",
  "skin flute",
  "snake",
  "snausage",
  "spitstick",
  "stem",
  "stretcher",
  "sucker",
  "swipe",
  "tadger",
  "tagger",
  "tail",
  "tallywhacker",
  "tarse",
  "thing",
  "thingy",
  "third leg",
  "tic tac",
  "todger",
  "tool",
  "trouser monkey",
  "trouser snake",
  "truncheon",
  "tube steak",
  "unit",
  "virile member",
  "wang",
  "weapon",
  "wee-wee",
  "weenie",
  "weeny",
  "whang",
  "wick",
  "widgie",
  "widdler",
  "wiener",
  "willie",
  "willy",
  "wingwang",
  "winkle",
  "winky",
  "yard",
  "ying-yang",
  "BBC",
  "BWC",
  "donkey cock",
  "donkey dick",
  "horse cock",
  "horse dick",
  "macropenis",
  "monster cock",
  "supercock",
  "superdick",
  "superpenis",
  "baby dick",
  "micropenis",
  "microphallus",
  "needle dick",
  "pencil dick",
  "dicksicle",
  "girldick",
  "cockshaft",
  "glans",
  "glans penis",
  "gock",
  "foreskin",
  "piss slit",
  "prepuce",
  "meatus",
  "shaft",
  "diller",
  "dillermand",
  "gøb",
  "javert",
  "kalorius",
  "kæp",
  "kødfløjte",
  "kønslem",
  "lem",
  "mandslem",
  "penis",
  "pik",
  "pikkemand",
  "tissemand"
];

//list is from https://en.wiktionary.org/wiki/Thesaurus:vagina
const vaginaList = [
  "axe wound",
  "bearded clam",
  "beaver",
  "berk",
  "bonne bouche",
  "box",
  "bun",
  "bush",
  "cavern",
  "clunge",
  "coin slot",
  "cooch",
  "coochie",
  "cookie",
  "cooter",
  "cooze",
  "crack",
  "crevice",
  "cunny",
  "cunt",
  "fanny",
  "foo-foo",
  "front bottom",
  "front bum",
  "front hole",
  "gash",
  "ginch",
  //"girl",
  "Grand Canyon",
  "honeypot",
  "hoo-ha",
  "innie",
  "juice box",
  "kebab",
  "kitty",
  "la-la",
  "love box",
  "love tunnel",
  "minge",
  "minnie",
  "monosyllable",
  "moocha",
  "muff",
  "muffin",
  "nonny",
  "pee-pee",
  "penis fly trap",
  "poontang",
  "pump",
  "punani",
  "pussy",
  "quim",
  "sausage wallet",
  "sheath",
  "slit",
  "snapper",
  "snatch",
  "squish mitten",
  "stench trench",
  "strange",
  "sugar walls",
  "tuppence",
  "trap",
  "twat",
  "twinkle",
  "vadge",
  "vag",
  "vagina",
  "vaginer",
  "va-jay-jay",
  "vertical smile",
  "vulva",
  "wee-wee",
  "whisker biscuit",
  "wizard's sleeve",
  "clitoris",
  "labia",
  "vulva",
  "birth canal",
  "doos",
  "kut",
  "kutje",
  "poesje",
  "preut",
  "pruim",
  "schede",
  "snee",
  "vagina",
  "bernarda",
  "cicala",
  "cosa",
  "farfalla",
  "fessa",
  "fica",
  "figa",
  "fregna",
  "gatta",
  "gnocca",
  "grembo",
  "micia",
  "mona",
  "mortaio",
  "natura",
  "passera",
  "patacca",
  "patata",
  "patonza",
  "pertugio",
  "potta",
  "pucchiacca",
  "sorca",
  "tana",
  "topa",
  "vulva",
  "vagina",
  "vulva",
  "aranha",
  "bacalhau",
  "berbigão",
  "boceta",
  "borboleta",
  "chaboita",
  "chana",
  "cona",
  "crica",
  "fenda",
  "fruto proibido",
  "greta",
  "mexilhão",
  "mona",
  "passarinha",
  "pepeca",
  "perereca",
  "periquita",
  "periquito",
  "perseguida",
  "pipi",
  "pito",
  "pomba",
  "rata",
  "racha",
  "tabaca",
  "xana",
  "xandanga",
  "xavasca",
  "xeca",
  "xereca",
  "xibiu",
  "xota",
  "almeja",
  "boba",
  "cajeta",
  "conejo",
  "chocha",
  "chochita mía",
  "chucha",
  "chorito",
  "choro",
  "concha",
  "coño",
  "devoratulas",
  "el corte inglés",
  "hachazo",
  "hueco",
  "kuku",
  "micha",
  "michoacán",
  "panocha",
  "papo",
  "peluche",
  "pucha",
  "sapo",
  "toto",
  "tontón",
  "zorra",
  "venocha",
  "zanja"
];

//list is from https://en.wiktionary.org/wiki/Thesaurus:breasts
const breastList = [
  "asset",
  "babylon",
  "balloon",
  "bap",
  "badonker",
  "bazonga",
  "bazooka",
  "bazoomba",
  "bazoom",
  "bewb",
  "boobage",
  "boob",
  "boober",
  "boobies",
  "boosies",
  "bosom",
  "breast",
  "breasticle",
  "bristol",
  "bubby",
  "bub",
  "bust",
  "calcium cannon",
  "cans",
  "charlie",
  "cheb",
  "chesticle",
  "chest melon",
  "chichi",
  "coconut",
  "diddy",
  "ding-dong",
  "dirty pillow",
  "funbag",
  "gazonga",
  //"girls",
  "globe",
  "headlight",
  "honker",
  "hooter",
  "itty-bitty",
  "jahoobies",
  "jigglies",
  "jubblies",
  "jugs",
  "knocker",
  "lady lumps",
  "love pillow",
  "mammaries",
  "mammary gland",
  "mammas",
  "megaboob",
  "melon",
  "milkbag",
  "milk jug",
  "milker",
  "mommy milker",
  "money maker",
  "mountain",
  "nork",
  "pap",
  "pair",
  "personality",
  "puppy",
  "rack",
  "sweater puppies",
  "tata",
  "teat",
  "tiddy",
  "tits",
  "titter",
  "titty",
  "threepenny bit",
  "top bollocks",
  "torpedo",
  "tract of land",
  "twins",
  "udder",
  "wap",
  "yabos",
  "bee stings",
  "falsies",
  "implants",
  "milk factories",
  "milk makers",
  "mosquito bites",
  "silicones",
  "mammary gland",
  "nipples",
  "body",
  "cleavage",
  "décolletage",
  "intermammary",
  "mastoid",
  "push-up",
  "spathic"
];